---
- name: disable ipv6
  lineinfile:
    dest=/etc/sysctl.conf
    insertbefore='^net.bridge.bridge-nf-call-ip6tables'
    line="net.ipv6.conf.all.disable_ipv6 = 1 ${LF}net.ipv6.conf.default.disable_ipv6 = 1"
    regexp='^net.ipv6.conf.all.disable_ipv6 = 1 ${LF}net.ipv6.conf.default.disable_ipv6 = 1'
  notify:
    - update sysctl

- name: disable bridge options
  lineinfile: backrefs=yes dest=/etc/sysctl.conf regexp='^(net.bridge.bridge-nf-call-ip6tables.*)' line="# \1"
- lineinfile: backrefs=yes dest=/etc/sysctl.conf regexp='^(net.bridge.bridge-nf-call-iptables.*)'  line="# \1"
- lineinfile: backrefs=yes dest=/etc/sysctl.conf regexp='^(net.bridge.bridge-nf-call-arptables.*)' line="# \1"
