---
- name: disable ipv6
  lineinfile:
    dest=/etc/sysctl.d/disableipv6.conf
    create=yes
    insertafter=EOF
    line="net.ipv6.conf.all.disable_ipv6=1"
    regexp='^net.ipv6.conf.all.disable_ipv6=1'
  notify:
    - update sysctl
