---
- name: "Create Application confg"
  template: >
    src=app-uwsgi.conf.j2
    dest=/etc/nginx/conf.d/{{ item.name }}.conf
    owner={{ app.user }}
    group={{ app.user }}
  with_items: _repos

- name: Check nginx config is valid
  action: command nginx -t

- include: ../handlers/main.yml
