---
- name: "Create Application confg"
  template: >
    src=app-uwsgi.conf.j2
    dest=/etc/nginx/conf.d/{{ app_name }}.conf
    owner={{ app.user }}
    group={{ app.user }}
  notify: reload nginx

- name: Check nginx config is valid
  action: command nginx -t
  register: nginxConfIsValid
