- name: Copy yum repository setting for nginx
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo

- name: install mongodb-client by yum
  yum: name=mongo-10gen state=installed

- name: install mongodb-server by yum
  yum: name=mongo-10gen-server state=installed
  when: _server is defined
