---
- name: "SymLink uwsgi.ini"
  file: >
    src=/home/{{ app.user }}/{{ item.name }}/uwsgi.ini
    dest=/etc/uwsgi/vassals/{{ item.name }}.ini
    owner={{ app.user }}
    group={{ app.user }}
    state=link
  with_items: _repos

- include: ../handlers/main.yml
