---
- name: "SymLink uwsgi.ini"
  file: >
    src=/home/{{ app.user }}/{{ app_name }}/uwsgi.ini
    dest=/etc/uwsgi/vassals/{{ app_name }}.ini
    owner={{ app.user }}
    group={{ app.user }}
    state=link
  notify: restart uwsgi
