---
- name: For all node
  hosts: all
  user: vagrant
  sudo: yes
  roles:
    - common
    - locale
    - application_user
    - rpmbuild
    - disable_ipv6
    - { role: iptables, _iptables: "${iptables.${ansible_os_family}}" }
