---
- name: For all node
  hosts: all
  user: vagrant
  sudo: yes
  roles:
    - common
    - locale
    - application_user
    - share_vagrant_dir
    - rpmbuild
    - disable_ipv6
    - { role: iptables, _iptables: "${iptables.${ansible_os_family}}" }

- name: Load Balancer
  hosts: loadbalancers
  user: vagrant
  sudo: yes
  roles:
    - nginx

- name: Application Server
  hosts: appservers
  user: vagrant
  sudo: yes
  roles:
    - python2.7
    - uwsgi
    - python_applications
    - mezzanine

- name: Database Server
  hosts: dbservers
  user: vagrant
  sudo: yes
  roles:
    - { role: mongodb, _server: true }

