---
- name: Install python-apt package
  raw: aptitude -y install python-apt
  ignore_errors: yes

- name: Install common packages (1/2)
  apt: name={{ item }} state=installed
  with_items: packages_common
  environment: env.apt

- name: Install common packages (2/2)
  apt: name={{ item }} state=installed
  with_items: packages_Debian
  environment: env.apt

- name: Start the ntp service
  service: name=ntp state=started enabled=true
  tags: ntp
