---
- name: "Enable google public dns"
  lineinfile: >
    dest=/etc/resolv.conf
    insertbefore='^nameserver'
    line='nameserver {{ item }}'
    regexp='^nameserver {{ item }}'
  with_items: dns.publics
  when: dns.use_public == True

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- include: Debian.yml
  when: ansible_os_family == "Debian"
- include: CentOS.yml
  when: ansible_os_family == "RedHat"
